### PR TITLE
Kerbalism support fix + textures to dds convert

### PR DESCRIPTION
**Pull request by Gordon-Dry**

### CODE REVIEW

**Comment by Gordon-Dry** [comment]
It's okay now.

I had some quirks because I had to make this work together with working on Kerbalism itself.

There was an obvious bracket error that didn't throw an MM error so I needed some time to recognize that.
And it was late.

**Comment by linuxgurugamer** [comment]
I'm going to wait a bit, just to be sure you don't find anything else

**Comment by Gordon-Dry** [comment]
There is something, the roataion animation of the centrifuge - when pressing ESC for the pause menu, the part continues rotating, but on another axis ...

Weird.

**Comment by linuxgurugamer** [comment]
Is this ready to commit now?

**Comment by Gordon-Dry** [comment]
Beside that weird animation thing, yes.

**Pull request merged**
